generate-root:
  tags:
    - cvmfs
  stage: .pre
  script:
    - source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
    - mkdir -p build install
    - cd build
    - >
        cmake -DCMAKE_INSTALL_PREFIX=../install
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always "
        -G Ninja ..
    - pwd
    - ls -al
    - cat /etc/*release
    - ninja -k0
    - ninja -k0 install
    - ninja -k0 && ctest --output-on-failure
    - wget https://hep-fcc.github.io/fcc-tutorials/_downloads/ce621667e828b2cd41e8cce63bf54a27/dd4hep2root
    - chmod u+x dd4hep2root
    - >
        ./dd4hep2root -c ../Detector/DetFCCeeIDEA-LAr/compact/FCCee_DectEmptyMaster.xml
        ../Detector/DetFCCeeECalInclined/compact/FCCee_ECalBarrel.xml
        -o fccee_lar.root
    - file fccee_lar.root
  artifacts:
    paths:
      - build/fccee_lar.root
    expire_in: 1 week

convert-gltf:
  dependencies:
    - generate-root
  stage: build
  image: registry.cern.ch/docker.io/library/fedora:latest
  script:
    - pwd
    - ls -al
    - ls -al ..
    - cat /etc/*release
    - cd ..
    # - dnf -y groupinstall "Development Tools"
    - dnf -y install git
    - dnf -y module install nodejs:16
    - git clone https://github.com/kjvbrt/root2gltf.git
    - cd root2gltf
    - node --version
    - npm --version
    - npm ci
    - node . -c config_example.json ../FCCDetectors/build/fccee_lar.root
    - file fccee_lar.gltf
