generate-root:
  tags:
    - cvmfs
  stage: .pre
  script:
    - source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
    - mkdir -p build install
    - cd build
    - >
        cmake -DCMAKE_INSTALL_PREFIX=../install
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always "
        -G Ninja ..
    - ninja -k0
    - ninja -k0 install
    - ninja -k0 && ctest --output-on-failure
    - cd ..
    - export FCCDETECTORS=`pwd`/install/share/FCCDetectors
    - export LD_LIBRARY_PATH=`pwd`/install/lib64:${LD_LIBRARY_PATH}
    - export LD_LIBRARY_PATH=`pwd`/install/lib:${LD_LIBRARY_PATH}
    - export PYTHONPATH=`pwd`/install/python:${PYTHONPATH}
    - >
        .github/scripts/dd4hep2root
        -c ${FCCDETECTORS}/Detector/DetFCCeeIDEA-LAr/compact/FCCee_DectEmptyMaster.xml
        ${FCCDETECTORS}/Detector/DetFCCeeECalInclined/compact/FCCee_ECalBarrel.xml
        -o fccee_lar.root
    - file fccee_lar.root
  artifacts:
    paths:
      - build/fccee_lar.root
    expire_in: 1 week

convert-gltf:
  dependencies:
    - generate-root
  stage: build
  image: registry.cern.ch/docker.io/library/fedora:latest
  script:
    - cd ..
    - dnf -y groupinstall "Development Tools"
    - dnf -y module install nodejs:16
    - git clone https://github.com/kjvbrt/root2gltf.git
    - cd root2gltf
    - npm ci
    - node . -c config_example.json ../FCCDetectors/build/fccee_lar.root
    - file fccee_lar.gltf

deploy-eos:
  dependencies:
    - convert-gltf
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
