build:
  tags:
    - cvmfs
  script:
    - source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
    - mkdir -p build install
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " \
            -G Ninja ..
