generate-root:
  tags:
    - cvmfs
  script:
    - source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
    - mkdir -p build install
    - cd build
    - >
        cmake -DCMAKE_INSTALL_PREFIX=../install
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always "
        -G Ninja ..
    - pwd
    - ls -al
    - cat /etc/*release
    - ninja -k0
    - ninja -k0 install
    - ninja -k0 && ctest --output-on-failure
    - wget https://hep-fcc.github.io/fcc-tutorials/_downloads/ce621667e828b2cd41e8cce63bf54a27/dd4hep2root
    - chmod u+x dd4hep2root
    - >
        ./dd4hep2root -c ../Detector/DetFCCeeIDEA-LAr/compact/FCCee_DectEmptyMaster.xml
        ../Detector/DetFCCeeECalInclined/compact/FCCee_ECalBarrel.xml
        -o fccee_lar.root
    - file fccee_lar.root
  artifacts:
    paths:
      - build/fccee_lar.root
    expire_in: 1 week

convert:
  dependencies:
    - generate-root
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cs8
  script:
    - pwd
    - ls -al
    - cat /etc/*release
#     - cd ../..
#     - git clone https://github.com/kjvbrt/root2gltf.git
#     - cd root2gltf
#     - yum install -y libX11-devel mesa-libGL-devel
#     - node --version
#     - npm --version
#     - npm ci
#     - node . ../FCCDetectors/build/fccee_lar.root
#     - file fccee_lar.gltf
